# Generated by Django 5.2.8 on 2025-11-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting for participant"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
